# Generated by Django 5.2.3 on 2025-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='generated_questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
