# Generated by Django 5.2.3 on 2025-07-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_generated_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
